# Generated by Django 3.0.8 on 2020-07-25 17:05

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.SlugField(default=student.models.random_student_code, unique=True),
        ),
    ]
